# SPDX-FileCopyrightText: 2025 LaCumbiaDelCoronavirus
# SPDX-FileCopyrightText: 2025 github_actions[bot]
# SPDX-FileCopyrightText: 2026 nabegator220
#
# SPDX-License-Identifier: MPL-2.0

# Used for mobs that can leap forward
- type: entity
  save: false
  id: MobLeaper
  abstract: true
  components:
  - type: JumpAbility
    action: ActionGravityDive
    canCollide: true
    jumpDistance: 1.25
    finishKnockdown: 0.85
    hitStaminaDamage: 0
    hitKnockdownDuration: 2
    jumpSound:
      path: /Audio/Weapons/punchmiss.ogg
      params:
        pitch: 1.33
        volume: -5
        variation: 0.05
