# SPDX-FileCopyrightText: 2022 Cheackraze
# SPDX-FileCopyrightText: 2022 OldDanceJacket
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 brainfood1183
# SPDX-FileCopyrightText: 2023 Checkraze
# SPDX-FileCopyrightText: 2023 Moony
# SPDX-FileCopyrightText: 2023 Scribbles0
# SPDX-FileCopyrightText: 2023 TsjipTsjip
# SPDX-FileCopyrightText: 2023 Ubaser
# SPDX-FileCopyrightText: 2023 deltanedas
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2024 Ed
# SPDX-FileCopyrightText: 2024 IProduceWidgets
# SPDX-FileCopyrightText: 2024 Southbridge
# SPDX-FileCopyrightText: 2024 TytosB
# SPDX-FileCopyrightText: 2025 ArtisticRoomba
# SPDX-FileCopyrightText: 2025 Deerstop
# SPDX-FileCopyrightText: 2025 Emisse
# SPDX-FileCopyrightText: 2025 FrauZj
# SPDX-FileCopyrightText: 2025 FrauzJ
# SPDX-FileCopyrightText: 2025 Kate
# SPDX-FileCopyrightText: 2025 LaCumbiaDelCoronavirus
# SPDX-FileCopyrightText: 2025 SlamBamActionman
# SPDX-FileCopyrightText: 2025 Spessmann
# SPDX-FileCopyrightText: 2025 compilatron
# SPDX-FileCopyrightText: 2025 lettuce
# SPDX-FileCopyrightText: 2025 nabegator220
# SPDX-FileCopyrightText: 2025 rottenheadphones
# SPDX-FileCopyrightText: 2026 github_actions[bot]
#
# SPDX-License-Identifier: MIT

- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Fland
  - Marathon
  - Packed
  - Reach
  - Snowball
  # KS14 restored maps
  - Saltern
  - Meta
  # KS14 removed maps
  # - Oasis
  # - Plasma
  # - Exo
  # KS14 ported Harmony maps
  - Mira
  - Omega
  - Spire
  - Jellyfish
  # KS14 ported Umbra maps
  - Wonderland
  # KS14 ported Moff maps
  - Frezon
